#!/usr/bin/env bash
set -euo pipefail

HASH_FILE="results/ARTIFACT_HASHES.md"

# Determine SHA256 command
if command -v sha256sum &>/dev/null; then
  SHA256="sha256sum"
elif command -v shasum &>/dev/null; then
  SHA256="shasum -a 256"
else
  echo "ERROR: no sha256sum or shasum found" >&2
  exit 1
fi

cat > "$HASH_FILE" << 'EOF'
# Artifact Hashes — Galaxy-X-os

Generated by `scripts/hash_artifacts.sh`. Verify with:

```bash
shasum -a 256 <file>   # macOS
sha256sum <file>       # Linux
```

## results/evaluation_results.json

```
SHA256: EVAL_HASH_PLACEHOLDER
```

## results/gradcam/_summary_grid.png

```
SHA256: GRADCAM_HASH_PLACEHOLDER
```

## checkpoints/best_model.pth

```
SHA256: CKPT_HASH_PLACEHOLDER
```

> **Note:** `checkpoints/best_model.pth` exceeds GitHub's 100 MB limit and is not
> committed. Download from
> [Release v1.0](https://github.com/Srujan0798/Galaxy-X-os/releases/tag/v1.0)
> or reproduce via the Colab notebook, then re-run this script.
EOF

eval_hash=$(eval "$SHA256" results/evaluation_results.json | cut -d' ' -f1)
gradcam_hash=$(eval "$SHA256" results/gradcam/_summary_grid.png | cut -d' ' -f1)

if [ -f checkpoints/best_model.pth ]; then
  ckpt_hash=$(eval "$SHA256" checkpoints/best_model.pth | cut -d' ' -f1)
else
  ckpt_hash="(unavailable — see note above)"
fi

sed -i '' "s/EVAL_HASH_PLACEHOLDER/$eval_hash/" "$HASH_FILE"
sed -i '' "s/GRADCAM_HASH_PLACEHOLDER/$gradcam_hash/" "$HASH_FILE"
sed -i '' "s/CKPT_HASH_PLACEHOLDER/$ckpt_hash/" "$HASH_FILE"

echo "Wrote $HASH_FILE"
echo "  eval_results.json   : $eval_hash"
echo "  _summary_grid.png  : $gradcam_hash"
echo "  best_model.pth      : $ckpt_hash"
